### ISSUE TITLE
Highlight differences betwen TinyCC and cjit

### ISSUE THREAD

**Issue by bakulf** [dyne/cjit#59]
TinyCC can already compile and run C files directly, and all the examples from the cjit documentation run correctly without cjit.

For instance:
* `curl https://raw.githubusercontent.com/dyne/cjit/refs/heads/main/examples/life.c | tcc -run -`
* `curl https://raw.githubusercontent.com/dyne/cjit/refs/heads/main/examples/sdl2_noise.c | tcc -run -`

Please write a better description/documentation highlighting the differences between the two projects.

**Comment by Morglod** [comment]
@bakulf @jaromil  looking at source and faq its not JIT. its tcc wrapped in single executable. there is no interpretation or even jit compilation because you cant interact between pushed expressions, there is no expressions pushed. in "interpreter mode" you just wrap code inside main and then compile and execute it. the fact that tcc is very fast does not make it jit. and there is nothing related to holyc which is really C interpreter with jit compiler. looking at code you know what you are doing, so you just lie here. why you do this?
